package in.ankushs.dbip.utils;


import com.google.common.collect.ImmutableMap;
import lombok.val;

import java.util.HashMap;
import java.util.Map;

public final class Country {

	private Country(){}

	private static final Map<String, String> countries;

	static {
		val temporary = new HashMap<String, String>();
		temporary.put("AF", "Afghanistan");
		temporary.put("AL", "Albania");
		temporary.put("DZ", "Algeria");
		temporary.put("AS", "American Samoa");
		temporary.put("AD", "Andorra");
		temporary.put("AO", "Angola");
		temporary.put("AI", "Anguilla ");
		temporary.put("AQ", "Antarctica");
		temporary.put("AG", "Antigua and Barbuda");
		temporary.put("AR", "Argentina");
		temporary.put("AM", "Armenia");
		temporary.put("AW", "Aruba");
		temporary.put("AU", "Australia");
		temporary.put("AT", "Austria");
		temporary.put("AZ", "Azerbaijan");
		temporary.put("BS", "Bahamas");
		temporary.put("BH", "Bahrain");
		temporary.put("BD", "Bangladesh");
		temporary.put("BB", "Barbados");
		temporary.put("BY", "Belarus");
		temporary.put("BE", "Belgium");
		temporary.put("BZ", "Belize");
		temporary.put("BJ", "Benin");
		temporary.put("BM", "Bermuda");
		temporary.put("BT", "Bhutan");
		temporary.put("BO", "'Bolivia, Plurinational State Of'  ");
		temporary.put("BQ", "'Bonaire, Saint Eustatius and Saba'");
		temporary.put("BA", "Bosnia and Herzegovina");
		temporary.put("BW", "Botswana");
		temporary.put("BV", "Bouvet Island");
		temporary.put("BR", "Brazil");
		temporary.put("IO", "British Indian Ocean Territory");
		temporary.put("BN", "Brunei Darussalam");
		temporary.put("BG", "Bulgaria");
		temporary.put("BF", "Burkina Faso");
		temporary.put("BI", "Burundi");
		temporary.put("KH", "Cambodia");
		temporary.put("CM", "Cameroon");
		temporary.put("CA", "Canada");
		temporary.put("CV", "Cape Verde  ");
		temporary.put("KY", "Cayman Islands");
		temporary.put("CF", "Central African Republic");
		temporary.put("TD", "Chad");
		temporary.put("CL", "Chile");
		temporary.put("CN", "China");
		temporary.put("CX", "Christmas Island");
		temporary.put("CC", "Cocos (Keeling) Islands");
		temporary.put("CO", "Colombia");
		temporary.put("KM", "Comoros");
		temporary.put("CG", "Congo");
		temporary.put("CD", "'Congo, The Democratic Republic Of The'");
		temporary.put("CK", "Cook Islands");
		temporary.put("CR", "Costa Rica");
		temporary.put("HR", "Croatia");
		temporary.put("CU", "Cuba");
		temporary.put("CW", "Curaçao");
		temporary.put("CY", "Cyprus");
		temporary.put("CZ", "Czech Republic");
		temporary.put("CI", "Côte D\'Ivoire");
		temporary.put("DK", "Denmark");
		temporary.put("DJ", "Djibouti");
		temporary.put("DM", "Dominica");
		temporary.put("DO", "Dominican Republic");
		temporary.put("EC", "Ecuador");
		temporary.put("EG", "Egypt");
		temporary.put("SV", "El Salvador");
		temporary.put("GQ", "Equatorial Guinea");
		temporary.put("ER", "Eritrea");
		temporary.put("EE", "Estonia");
		temporary.put("ET", "Ethiopia");
		temporary.put("FK", "Falkland Islands  (Malvinas)");
		temporary.put("FO", "Faroe Islands");
		temporary.put("FJ", "Fiji");
		temporary.put("FI", "Finland");
		temporary.put("FR", "France");
		temporary.put("GF", "French Guiana");
		temporary.put("PF", "French Polynesia");
		temporary.put("TF", "French Southern Territories");
		temporary.put("GA", "Gabon");
		temporary.put("GM", "Gambia");
		temporary.put("GE", "Georgia");
		temporary.put("DE", "Germany");
		temporary.put("GH", "Ghana ");
		temporary.put("GI", "Gibraltar");
		temporary.put("GR", "Greece");
		temporary.put("GL", "Greenland");
		temporary.put("GD", "Grenada");
		temporary.put("GP", "Guadeloupe");
		temporary.put("GU", "Guam");
		temporary.put("GT", "Guatemala");
		temporary.put("GG", "Guernsey");
		temporary.put("GN", "Guinea");
		temporary.put("GW", "Guinea-Bissau");
		temporary.put("GY", "Guyana");
		temporary.put("HT", "Haiti");
		temporary.put("HM", "Heard and McDonald Islands");
		temporary.put("VA", "Holy See (Vatican City State)");
		temporary.put("HN", "Honduras");
		temporary.put("HK", "Hong Kong");
		temporary.put("HU", "Hungary");
		temporary.put("IS", "Iceland");
		temporary.put("IN", "India");
		temporary.put("ID", "Indonesia");
		temporary.put("IR", "'Iran, Islamic Republic Of'");
		temporary.put("IQ", "Iraq");
		temporary.put("IE", "Ireland");
		temporary.put("IM", "Isle of Man");
		temporary.put("IL", "Israel");
		temporary.put("IT", "Italy");
		temporary.put("JM", "Jamaica");
		temporary.put("JP", "Japan");
		temporary.put("JE", "Jersey");
		temporary.put("JO", "Jordan");
		temporary.put("KZ", "Kazakhstan");
		temporary.put("KE", "Kenya");
		temporary.put("KI", "Kiribati");
		temporary.put("KP", "'Korea, Democratic People\'s Republic Of'");
		temporary.put("KR", "'Korea, Republic of'");
		temporary.put("KW", "Kuwait");
		temporary.put("KG", "Kyrgyzstan");
		temporary.put("LA", "Lao People\'s Democratic Republic");
		temporary.put("LV", "Latvia");
		temporary.put("LB", "Lebanon");
		temporary.put("LS", "Lesotho");
		temporary.put("LR", "Liberia");
		temporary.put("LY", "Libyan Arab Jamahiriya");
		temporary.put("LI", "Liechtenstein");
		temporary.put("LT", "Lithuania");
		temporary.put("LU", "Luxembourg");
		temporary.put("MO", "Macao");
		temporary.put("MK", "'Macedonia, the Former Yugoslav Republic Of'");
		temporary.put("MG", "Madagascar");
		temporary.put("MW", "Malawi");
		temporary.put("MY", "Malaysia");
		temporary.put("MV", "Maldives");
		temporary.put("ML", "Mali");
		temporary.put("MT", "Malta");
		temporary.put("MH", "Marshall Islands");
		temporary.put("MQ", "Martinique");
		temporary.put("MR", "Mauritania");
		temporary.put("MU", "Mauritius");
		temporary.put("YT", "Mayotte");
		temporary.put("MX", "Mexico");
		temporary.put("FM", "'Micronesia, Federated States Of'");
		temporary.put("MD", "'Moldova, Republic of'");
		temporary.put("MC", "Monaco");
		temporary.put("MN", "Mongolia");
		temporary.put("ME", "Montenegro");
		temporary.put("MS", "Montserrat");
		temporary.put("MA", "Morocco");
		temporary.put("MZ", "Mozambique");
		temporary.put("MM", "Myanmar");
		temporary.put("NA", "Namibia");
		temporary.put("NR", "Nauru");
		temporary.put("NP", "Nepal");
		temporary.put("NL", "Netherlands");
		temporary.put("AN", "Netherlands Antilles");
		temporary.put("NC", "New Caledonia");
		temporary.put("NZ", "New Zealand");
		temporary.put("NI", "Nicaragua");
		temporary.put("NE", "Niger");
		temporary.put("NG", "Nigeria");
		temporary.put("NU", "Niue");
		temporary.put("NF", "Norfolk Island");
		temporary.put("MP", "Northern Mariana Islands");
		temporary.put("NO", "Norway");
		temporary.put("OM", "Oman");
		temporary.put("PK", "Pakistan");
		temporary.put("PW", "Palau");
		temporary.put("PS", "'Palestinian Territory, Occupied'");
		temporary.put("PA", "Panama");
		temporary.put("PG", "Papua New Guinea");
		temporary.put("PY", "Paraguay");
		temporary.put("PE", "Peru");
		temporary.put("PH", "Philippines");
		temporary.put("PN", "Pitcairn");
		temporary.put("PL", "Poland");
		temporary.put("PT", "Portugal");
		temporary.put("PR", "Puerto Rico");
		temporary.put("QA", "Qatar");
		temporary.put("RO", "Romania");
		temporary.put("RU", "Russian Federation");
		temporary.put("RW", "Rwanda");
		temporary.put("RE", "Réunion");
		temporary.put("BL", "Saint Barthélemy");
		temporary.put("SH", "'Saint Helena, Ascension and Tristan Da Cunha'");
		temporary.put("KN", "Saint Kitts And Nevis");
		temporary.put("LC", "Saint Lucia");
		temporary.put("MF", "Saint Martin");
		temporary.put("PM", "Saint Pierre And Miquelon");
		temporary.put("VC", "Saint Vincent And The Grenedines");
		temporary.put("WS", "Samoa");
		temporary.put("SM", "San Marino");
		temporary.put("ST", "Sao Tome and Principe");
		temporary.put("SA", "Saudi Arabia");
		temporary.put("SN", "Senegal");
		temporary.put("RS", "Serbia");
		temporary.put("SC", "Seychelles");
		temporary.put("SL", "Sierra Leone");
		temporary.put("SG", "Singapore");
		temporary.put("SX", "Sint Maarten (Dutch part)");
		temporary.put("SK", "Slovakia");
		temporary.put("SI", "Slovenia");
		temporary.put("SB", "Solomon Islands");
		temporary.put("SO", "Somalia");
		temporary.put("ZA", "South Africa");
		temporary.put("GS", "South Georgia and the South Sandwich Islands");
		temporary.put("ES", "Spain");
		temporary.put("LK", "Sri Lanka");
		temporary.put("SD", "Sudan");
		temporary.put("SR", "Suriname");
		temporary.put("SJ", "Svalbard And Jan Mayen");
		temporary.put("SZ", "Swaziland");
		temporary.put("SE", "Sweden");
		temporary.put("CH", "Switzerland");
		temporary.put("SY", "Syrian Arab Republic  ");
		temporary.put("TW", "'Taiwan, Province Of China'");
		temporary.put("TJ", "Tajikistan");
		temporary.put("TZ", "'Tanzania, United Republic of'");
		temporary.put("TH", "Thailand");
		temporary.put("TL", "Timor-Leste");
		temporary.put("TG", "Togo");
		temporary.put("TK", "Tokelau");
		temporary.put("TO", "Tonga");
		temporary.put("TT", "Trinidad and Tobago");
		temporary.put("TN", "Tunisia");
		temporary.put("TR", "Turkey");
		temporary.put("TM", "Turkmenistan");
		temporary.put("TC", "Turks and Caicos Islands");
		temporary.put("TV", "Tuvalu");
		temporary.put("UG", "Uganda");
		temporary.put("UA", "Ukraine");
		temporary.put("AE", "United Arab Emirates");
		temporary.put("GB", "United Kingdom");
		temporary.put("US", "United States");
		temporary.put("UM", "United States Minor Outlying Islands");
		temporary.put("UY", "Uruguay");
		temporary.put("UZ", "Uzbekistan");
		temporary.put("VU", "Vanuatu");
		temporary.put("VE", "'Venezuela, Bolivarian Republic of' ");
		temporary.put("VN", "Viet Nam");
		temporary.put("VG", "'Virgin Islands, British'");
		temporary.put("VI", "'Virgin Islands, U.S.'");
		temporary.put("WF", "Wallis and Futuna");
		temporary.put("EH", "Western Sahara");
		temporary.put("YE", "Yemen");
		temporary.put("ZM", "Zambia");
		temporary.put("ZW", "Zimbabwe");
		temporary.put("AX", "Åland Islands");
		countries = ImmutableMap.copyOf(temporary);
	}
	
	public static String from(final String code) {
		Assert.notEmptyString(code, "no countryCode provided");
		val value = countries.get(code);
		return !Strings.hasText(value) ? Strings.EMPTY : value;
	}
}
